Olympus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('users.urls', namespace='users')),
    path('', include('carrito.urls', namespace='carrito')),
    path('api/', include('api_rest.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrito/urls.py
from django.urls import path, include
from .views import agregar_producto, eliminar_producto, restar_producto,limpiar_carrito,añadir_producto, agregar_producto_varios

app_name = 'carrito'

urlpatterns = [
    path('agregar_producto/<int:idProducto>/', agregar_producto, name="agregar_producto"),
    path('eliminar_producto/<int:idProducto>/', eliminar_producto, name="eliminar_producto"),
    path('restar_producto/<int:idProducto>/', restar_producto, name="restar_producto"),
    path('limpiar_carrito', limpiar_carrito, name="limpiar_carrito"),
    path('añadir_producto/<int:idProducto>/', añadir_producto, name="añadir_producto"),
    path('agregar_producto_varios/<int:idProducto>/', agregar_producto_varios, name="agregar_producto_varios"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import cuentaView, editarCuentaFormView, index, iniciarSesion, cambiarClave, recuperarClave, categoriaProducto, producto, agregarProducto, registrarP, catalogoPoleras, catalogoPantalones, catalogoZapatillas, catalogoPolerones, catalogoChaquetas, cuenta, contacto, carrito, editarProducto, editarP, eliminarProducto, enviarCon, msjFooter, editarUsuario, registroFormView, msjClave, requiereLogin

app_name = 'core'

urlpatterns = [
    path('', index, name="index"),
    path( 'iniciarSesion', iniciarSesion, name="iniciarSesion"),
    path( 'cambiarClave', cambiarClave, name="cambiarClave"),
    path( 'recuperarClave', recuperarClave, name="recuperarClave"),
    path( 'registro', registroFormView.as_view(), name="registro"),
    path( 'categoriaProducto', categoriaProducto, name="categoriaProducto"),
    path( 'producto/<int:id>', producto, name="producto"),
    path( 'agregarProducto', agregarProducto, name="agregarProducto"),
    path( 'registrarP', registrarP, name="registrarP"),
    path( 'catalogoPoleras', catalogoPoleras, name="catalogoPoleras"),
    path( 'catalogoPantalones', catalogoPantalones, name="catalogoPantalones"),
    path( 'catalogoZapatillas', catalogoZapatillas, name="catalogoZapatillas"),
    path( 'catalogoPolerones', catalogoPolerones, name="catalogoPolerones"),
    path( 'catalogoChaquetas', catalogoChaquetas, name="catalogoChaquetas"),
    path( 'cuenta', cuentaView.as_view(), name="cuenta"),
    path( 'editarCuenta', editarCuentaFormView.as_view(), name="editarCuenta"),
    path( 'editarUsuario/<int:id>', editarUsuario, name="editarUsuario"),
    path( 'contacto', contacto, name="contacto"),
    path( 'carrito', carrito, name="carrito"),
    path( 'editarProducto/<int:id>', editarProducto, name='editarProducto'),
    path( 'editarP/<int:id>', editarP, name='editarP'),
    path( 'eliminarProducto/<int:id>', eliminarProducto, name='eliminarProducto'),
    path( 'enviarCon', enviarCon, name="enviarCon"),
    path( 'msjFooter', msjFooter, name="msjFooter"),
    path( 'msjClave', msjClave, name="msjClave"),
    path( 'requiereLogin', requiereLogin, name="requiereLogin")
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'), # Iniciar Sesión
    path('profile/', views.profile_view, name='profile'), # Ver Perfil de Usuario
    path('signup/', views.signup_view, name='signup'), # Registrar Usuario
    path('logout/', views.logout_view, name='logout'), # Cerrar Sesión
    path('changePassword/<int:id>', views.profile_change_password, name='changePassword') # cambiar contraseña
]

core/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    idCategoria = models.IntegerField(primary_key=True,verbose_name="Código de la Categoría")
    nombreC = models.CharField(max_length=30, verbose_name="Nombre de la Categoría",null=False, blank=False)

    def __str__(self):
        return self.nombreC

class Estatus(models.Model):
    idEstatus = models.IntegerField(primary_key=True,verbose_name="Código de la Categoría")
    nombreE = models.CharField(max_length=30, verbose_name="Nombre del Estatus",null=False, blank=False)

    def __str__(self):
        return self.nombreE

class Producto(models.Model):
    idProducto = models.AutoField(primary_key=True, verbose_name='Código del Producto')
    nombreProducto = models.CharField(max_length=30, verbose_name='Nombre del Producto')
    descCorta = models.CharField(max_length=30, verbose_name='Descripción Corta del Producto')
    descLarga = models.CharField(max_length=200, verbose_name='Descripción Detallada del Producto')
    precio = models.IntegerField(verbose_name='Precio del Producto')
    stock = models.IntegerField(verbose_name='Cantidad en Stock del Producto')
    foto = models.ImageField(upload_to="core/", default='core/default.png',null= True)
    categoria = models.ForeignKey(Categoria,on_delete= models.CASCADE)
    estatus = models.ForeignKey(Estatus,on_delete= models.PROTECT)

    def __str__(self):
        return self.nombreProducto

carrito/views.py
from django.shortcuts import render
from .carrito import Carrito
from core.models import Producto
from django.shortcuts import redirect
from django.contrib import messages
# Create your views here.
def agregar_producto(request, idProducto):
    carrito=Carrito(request)

    producto=Producto.objects.get(idProducto=idProducto)
    carrito.agregarProducto(producto=producto)
    messages.success(request, 'Producto Agregado al carrito')
    return redirect(request.META.get('HTTP_REFERER'))

def agregar_producto_varios(request, idProducto):
    numero = request.POST['formCantidad']
    numero = int(numero)
    
    carrito=Carrito(request)
    producto=Producto.objects.get(idProducto=idProducto)
    carrito.agregarProductoVarios(producto=producto, numero=numero)
    
    messages.success(request, 'Producto Agregado al carrito')
    return redirect(request.META.get('HTTP_REFERER'))

def añadir_producto(request, idProducto):
    carrito=Carrito(request)

    producto=Producto.objects.get(idProducto=idProducto)
    carrito.agregarProducto(producto=producto)
    return redirect(request.META.get('HTTP_REFERER'))

def eliminar_producto(request, idProducto):
    carrito=Carrito(request)

    producto=Producto.objects.get(idProducto=idProducto)
    carrito.eliminarProducto(producto=producto)
    return redirect(request.META.get('HTTP_REFERER'))

def restar_producto(request, idProducto):
    carrito=Carrito(request)

    producto=Producto.objects.get(idProducto=idProducto)
    carrito.restar_producto(producto=producto)
    return redirect(request.META.get('HTTP_REFERER'))

def limpiar_carrito(request):
    carrito=Carrito(request)
    carrito.limpiar_carrito()
    messages.success(request, 'Carrito Vaciado')
    return redirect(request.META.get('HTTP_REFERER'))
    

core/views.py
from email import message
from multiprocessing import context
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from .models import Estatus, Producto, Categoria, Categoria
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from users.models import Direccion, UserProfile

from users.models import Comuna, Region, UserProfile
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
#from context_processors import login_user

# Create your views here.
def index(request):
    return render(request,'core/index.html')
    
def iniciarSesion(request):
    return render(request,'core/iniciarSesion.html')

def cambiarClave(request):
    return render(request,'core/cambiarClave.html')

def recuperarClave(request):
    return render(request,'core/recuperarClave.html')

def categoriaProducto(request):
    return render(request,'core/categoriaProducto.html')

def producto(request, id):
    producto = Producto.objects.get(idProducto = id)
    contexto = {"producto":producto}  
    return render(request,'core/producto.html', contexto)

def agregarProducto(request):
    categorias = Categoria.objects.all()
    contexto = {"categoria_p":categorias}
    return render(request,'core/agregarProducto.html',contexto)

def registrarP(request):
    nombre = request.POST['nombreProducto']
    descripcionC = request.POST['descripcionCorta']
    descripcionL = request.POST['descripcionDetallada']
    precio = request.POST['precioP']
    stock = request.POST['cantidad']
    foto = request.FILES['fotoInput']
    categoria = request.POST['categoria']

    categoria2 = Categoria.objects.get(idCategoria = categoria)

    estatus = Estatus.objects.get(idEstatus = 1)

    Producto.objects.create(nombreProducto = nombre, descCorta = descripcionC, descLarga = descripcionL, precio = precio, stock = stock, foto = foto, categoria = categoria2, estatus = estatus)
    messages.success(request,'Producto Agregado')
    return redirect('core:agregarProducto')

def catalogoChaquetas(request):
    id_categoria = Categoria.objects.get(idCategoria = 1)
    chaquetas = Producto.objects.filter(categoria = id_categoria, stock__gte = 1, estatus=1) #Seleccionar todas las chaquetas
    contexto = {"chaquetas":chaquetas}
    return render(request,'core/catalogoChaquetas.html', contexto)

def catalogoPantalones(request):
    id_categoria = Categoria.objects.get(idCategoria = 2)
    pantalones = Producto.objects.filter(categoria = id_categoria, stock__gte = 1, estatus=1) #Seleccionar todos los pantalones
    contexto = {"pantalones":pantalones}
    return render(request,'core/catalogoPantalones.html', contexto)

def catalogoPoleras(request):
    id_categoria = Categoria.objects.get(idCategoria = 3)
    poleras = Producto.objects.filter(categoria = id_categoria, stock__gte = 1, estatus=1) #Seleccionar todas las poleras
    contexto = {"poleras":poleras}
    return render(request,'core/catalogoPoleras.html', contexto)

def catalogoPolerones(request):
    id_categoria = Categoria.objects.get(idCategoria = 4)
    polerones = Producto.objects.filter(categoria = id_categoria, stock__gte = 1, estatus=1) #Seleccionar todos los polerones
    contexto = {"polerones":polerones}
    return render(request,'core/catalogoPolerones.html', contexto)

def catalogoZapatillas(request):
    id_categoria = Categoria.objects.get(idCategoria = 5)
    zapatillas = Producto.objects.filter(categoria = id_categoria, stock__gte = 1, estatus=1) #Seleccionar todas las zapatillas
    contexto = {"zapatillas":zapatillas}
    return render(request,'core/catalogoZapatillas.html', contexto)

def carrito(request):
    return render(request,'core/carrito.html')

def contacto(request):

    return render(request,'core/contacto.html')

def enviarCon(request):

    asunto = request.POST['asunto']
    mensaje = request.POST['mensaje']+ '\r\n' + 'Nombre De Contacto: ' + request.POST['nombre'] + ' Correo De Contacto: ' + request.POST['email']
    emisor =settings.EMAIL_HOST_USER
    receptor =['lu.morgado@duocuc.cl', 'fa.marileo@duocuc.cl']
    
    send_mail(asunto, mensaje, emisor, receptor)
    messages.success(request,'Mensaje Enviado')
    return redirect('core:contacto')

def editarProducto(request, id):
    categorias = Categoria.objects.all()
    producto = Producto.objects.get(idProducto = id)
    contexto = {"producto":producto, "categoria_p":categorias}  
    return render(request, 'core/editarProducto.html', contexto)

def editarP(request, id):
    nombre = request.POST['nombreProducto']
    descripcionC = request.POST['descripcionCorta']
    descripcionL = request.POST['descripcionDetallada']
    precio = request.POST['precioP']
    stock = request.POST['cantidad']

    categoria = request.POST['categoria']

    try:

        categoria2 = Categoria.objects.get(idCategoria = categoria)

    # obtener el registro de la base de datos
        producto = Producto.objects.get(idProducto = id)

    # reemplazar valores en el registro
        producto.nombreProducto = nombre
        producto.descCorta = descripcionC
        producto.descLarga = descripcionL
        producto.precio = precio
        producto.stock = stock
        producto.categoria = categoria2

        foto = request.FILES['fotoInput']
        producto.foto = foto
    except:
        foto = "No hay cambio"

    #update
    producto.save() 
    messages.success(request, 'Producto modificado')
    return redirect('core:editarProducto',id)

def eliminarProducto(request, id):
    producto = Producto.objects.get(idProducto = id)
    estatus = Estatus.objects.get(idEstatus = 2)
    
    producto.estatus = estatus
    producto.save()
    messages.success(request, 'Producto eliminado')
    if producto.categoria.idCategoria == 1:
        return redirect('core:catalogoChaquetas')
    elif producto.categoria.idCategoria == 2:
        return redirect('core:catalogoPantalones')
    elif producto.categoria.idCategoria == 3:
        return redirect('core:catalogoPoleras')
    elif producto.categoria.idCategoria == 2:
        return redirect('core:catalogoPolerones')
    elif producto.categoria.idCategoria == 2:
        return redirect('core:catalogoZapatillas')

def msjFooter(request):

    asunto = 'Suscripcion Realizada'
    mensaje = 'Usted se ha suscrito correctamente, Pronto le llegaran las nuevas ofertas.'
    emisor =settings.EMAIL_HOST_USER
    rec = request.POST['emailF']
    receptor = [rec]
    pagAnt =request.POST['pagAnt']
    send_mail(asunto, mensaje, emisor, receptor)
    messages.success(request,'Suscripcion Realizada')
    
   
    return redirect(pagAnt)


def editarUsuario(request, id):
    nombre = request.POST['nombre']
    apellidoPa = request.POST['apellidoPa']
    telefono = request.POST['telefono']

    try:
        usuario = UserProfile.objects.get(id = id)
        usuario.nombre = nombre
        usuario.apellidoPa = apellidoPa
        usuario.telefono = telefono

        foto = request.FILES['fotoInput']
        usuario.foto = foto

    except:
        foto = "No hay cambio"
    #update de los campos de usuario     
    usuario.save()

    try:
        direc = request.POST['direccion']
        comuna = request.POST['comuna']
        direccionUsuario = Direccion.objects.get(idUsuario = id)
        comuna1 = Comuna.objects.get(nombre = comuna)
        direccionUsuario.nombre = direc
        direccionUsuario.comuna = comuna1
        direccionUsuario.save()
    except:
        None
    #update de los campos de direccion  
    messages.success(request,'Cambios Guardados')
    return redirect('core:cuenta')


@method_decorator(csrf_exempt, name='dispatch')
class registroFormView(TemplateView):
    template_name = 'core/registro.html'

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'buscar_comuna_id':
                data = []
                for i in Comuna.objects.filter(region= request.POST['id']):
                    data.append({'id': i.idComuna, 'nombre': i.nombre })
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = 'Ha ocurrido un error'
        return JsonResponse(data, safe=False)

@method_decorator(csrf_exempt, name='dispatch')
class editarCuentaFormView(TemplateView):
    template_name = 'core/editarCuenta.html'

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'buscar_comuna_id':
                data = []
                for i in Comuna.objects.filter(region= request.POST['id']):
                    data.append({'id': i.idComuna, 'nombre': i.nombre })
                return JsonResponse(data, safe=False)
            
            if action == 'buscar_direccion':
                data = []
                direccion = Direccion.objects.get(email = request.POST['email'])
                comuna = Comuna.objects.get(nombre = direccion.comuna)
                region = Region.objects.get(nombre = comuna.region)
                return JsonResponse({'direccionU':direccion.nombre, 'comunaU':comuna.idComuna, 'regionU':region.idRegion })
            else:
                data['error'] = 'Ha ocurrido un error'
                return JsonResponse(data, safe=False)
        except:
            data['error'] = 'Ha ocurrido un error'
            return JsonResponse(data, safe=False)


def cuenta(request):
    return render(request,'core/cuenta.html')

def msjClave(request):

    asunto = 'Solicitud Contraseña'
    mensaje = 'Su solicitud ha sido recibida, pronto recibira su contraseña.'
    emisor =settings.EMAIL_HOST_USER
    rec = request.POST['correo1']
    receptor = [rec]
    send_mail(asunto, mensaje, emisor, receptor)
    messages.success(request,'Correo Enviado')

core/templates/core/Producto.html
{% extends 'core/plantillaProducto.html' %}
{% load static %}
  

  {% block cabecera %}
  <title>Olympus</title>
  {% endblock cabecera %}

      {% block detalleProducto %}
      <div class="row">
        <div class="col-md-6 col-sm-12 mt-3 mb-3">
          {% if producto.foto %}
            <div class="ratio ratio-1x1"><img src="{{ producto.foto.url }}" class="img-thumbnail" alt="..."></div>
          {% else %}
            <div class="ratio ratio-1x1"><img src="/media/core/default.png" class="img-thumbnail" alt="..."></div>
          {% endif %}
        </div>
        <div class="col-md-6 col-sm-12 mt-3 mb-3">
          <div class="row row px-3">
            <h3>
              {{ producto.nombreProducto }}
            </h3>
            <p style="color: rgb(0, 100, 255); font-size: 120%;">
              ${{ producto.precio }}
            </p>
            <h5>
              {{ producto.descCorta }}
            </h5>
            <p>
              {{ producto.descLarga }}
            </p>
            <h5>
              Disponibilidad: {{ producto.stock }}
            </h5>
      
            {% if user.is_authenticated and user.is_staff == 0 %}
              <b>Seleccionar Cantidad</b>
              <form action="{% url 'carrito:agregar_producto_varios' producto.idProducto %}" method="POST">
              {% csrf_token %} 
                <div class="form-outline">
                  <input id="formCantidad" min="1" max="{{ producto.stock }}" name="formCantidad" value="1" type="number" class="form-control mb-3" />
                </div>
                <button type="submit" class="btn btn-primary ">Agregar al Carro</button>
              </form>
            {% elif user.is_authenticated and user.is_staff == 1 %}

            {% else %}
              <b>Seleccionar Cantidad</b>
              <form action="" method="POST">
              {% csrf_token %} 
                <div class="form-outline">
                  <input id="formCantidad" min="1" max="{{ producto.stock }}" name="formCantidad" value="1" type="number" class="form-control mb-3" />
                </div>
                  <a href="{% url 'core:requiereLogin' %}" class="btn btn-primary">Agregar al Carro</a>
              </form>
            {% endif %}
          </div>
        </div>
      </div>
      {% endblock detalleProducto %}
    

core/templates/core/carrito.html
<!DOCTYPE html>
<html lang="es">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Olympus</title>
  <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
  <script src="https://kit.fontawesome.com/35863c2e47.js" crossorigin="anonymous"></script>
  <link rel="icon" href="{% static 'core/img/logo.png' %}">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>

<body>
  {% include 'core/navbar.html' %}

  <!--
    ======================================================================================================= -->
  <!--CARRO DE COMPRAS -->
  <!--
    ======================================================================================================= -->

  <section class="h-100">
    <div class="container py-5">
      <div class="row d-flex justify-content-center my-4">
        <div class="col-md-12">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Carrito de Compra</h5>
            </div>
            <table class="table table-bordered" style="color: rgb(0, 0, 0);">
              <thead>
                <tr>
                  <th>Foto Producto</th>
                  <th>Nombre Producto</th>
                  <th>Cantidad</th>
                  <th>Suma</th>
                </tr>
              </thead>
              <tbody>
                {% if request.session.carrito.items %}
                {% for key, value in request.session.carrito.items %}
                <tr class="text-center">
                  <td><img src="{{value.imagen}}" class="img-carrito" alt="Imagen Producto"></td>
                  <td>{{value.nombreProducto}}</td>
                  <td>{{value.cantidad}}</td>
                  <td>
                    ${{value.precio}}
                  </td>
                  <td>
                    <a href="{% url 'carrito:añadir_producto' value.idProducto %}" class="btn btn-sm btn-primary">+</a>
                    <a href="{% url 'carrito:restar_producto' value.idProducto %}"
                      class="btn btn-sm btn-primary">-</a><br />
                    <a href="{% url 'carrito:eliminar_producto' value.idProducto %}"
                      class="btn btn-sm btn-danger m-3">Eliminar Producto</a>
                  </td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                  <td colspan="4">
                    <div class="alert alert-danger text-center">
                      Sin productos
                    </div>
                  </td>
                </tr>
                {% endif %}
              </tbody>
            </table>
            <a href="{% url 'carrito:limpiar_carrito' %}" class="btn btn-sm btn-primary">Limpiar Carrito</a>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body">
            <p><strong>Metodos de Pago</strong></p>
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
              alt="Visa" />
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
              alt="Mastercard" />
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Resumen</h5>
          </div>
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                Productos
                <span>${{total_carrito}}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                Envio
                <span>
                  {% if total_carrito > 30000 %}
                  Gratis
                  {% else %}
                  ${{despacho}}
                  {% endif %}
                </span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                <div>
                  <strong>Total a Pagar</strong>
                  <strong>
                    <p class="mb-0">(incluyendo IVA)</p>
                  </strong>
                </div>
                <span><strong>
                  {% if total_carrito > 30000 %}
                    ${{total_carrito}}
                  {% else %}
                    ${{total_carrito|add:"5000"}} 
                  {% endif %}</strong></span>
              </li>
            </ul>

            <button type="button" class="btn btn-primary btn-lg btn-block">
              Ir a Pagar
            </button>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>


  {% include 'core/footer.html' %}
</body>

</html>

core/templates/core/catalogoPantalones.html
{% extends 'core/plantillaCategoriaProducto.html' %}
{% load static %}

{% block catalogo %}
<div class="container-fluid">
  <div class="row row-cols-2 row-cols-md-4 mt-2 mb-4 gy-3">
    {% for p in pantalones %}
    <div class="col">
      <div class="card h-100">
        <div class="text-center">
          {% if p.foto %}
            <a href="{% url 'core:producto' p.idProducto %}"><img src="{{ p.foto.url }}" class="card-img-top " alt="...">
          {% else %}
            <a href="{% url 'core:producto' p.idProducto %}"><img src="/media/core/default.png" class="card-img-top " alt="...">
          {% endif %}
            <div class="overlay">
              Click para ver producto
            </div>
          </a>
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ p.nombreProducto }}</h5>
          <p class="card-text">{{ p.descCorta }}</p>
          <p class="card-text" style="color: rgb(211, 20, 20); font-size: 150%;">${{ p.precio }}</p>
          {% if user.is_authenticated and user.is_staff == 1 %}
          <div class="row">
            <a href="{% url 'core:editarProducto' p.idProducto %}" class="btn btn-primary my-1">Editar</a>
            <a href="{% url 'core:eliminarProducto' p.idProducto %}" class="btn btn-danger my-1">Eliminar</a>
          </div>
          {% elif user.is_authenticated %}
            <a href="{% url 'carrito:agregar_producto' p.idProducto %}" class="btn btn-primary">Agregar al Carro</a>
          {% else %}
            <a href="{% url 'core:requiereLogin' %}" class="btn btn-primary">Agregar al Carro</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock catalogo %}

core/templates/core/catalogoPolerones.html
{% extends 'core/plantillaCategoriaProducto.html' %}
{% load static %}

{% block catalogo %}
<div class="container-fluid">
  <div class="row row-cols-2 row-cols-md-4 mt-2 mb-4 gy-3">
    {% for p in polerones %}
    <div class="col">
      <div class="card h-100">
        <div class="text-center">
          {% if p.foto %}
            <a href="{% url 'core:producto' p.idProducto %}"><img src="{{ p.foto.url }}" class="card-img-top " alt="...">
          {% else %}
            <a href="{% url 'core:producto' p.idProducto %}"><img src="/media/core/default.png" class="card-img-top " alt="...">
          {% endif %}
            <div class="overlay">
              Click para ver producto
            </div>
          </a>
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ p.nombreProducto }}</h5>
          <p class="card-text">{{ p.descCorta }}</p>
          <p class="card-text" style="color: rgb(211, 20, 20); font-size: 150%;">${{ p.precio }}</p>
          {% if user.is_authenticated and user.is_staff == 1 %}
          <div class="row">
            <a href="{% url 'core:editarProducto' p.idProducto %}" class="btn btn-primary my-1">Editar</a>
            <a href="{% url 'core:eliminarProducto' p.idProducto %}" class="btn btn-danger my-1">Eliminar</a>
          </div>
          {% elif user.is_authenticated %}
            <a href="{% url 'carrito:agregar_producto' p.idProducto %}" class="btn btn-primary">Agregar al Carro</a>
          {% else %}
            <a href="{% url 'core:requiereLogin' %}" class="btn btn-primary">Agregar al Carro</a>
          {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock catalogo %}